apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repository
spec:
  resources:
    requests:
      storage: 100Mi
  storageClassName: standart-rwo
  accessModes:
    - ReadWriteOnce
       
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ricardomarino/backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: ricardomarino/database:1.0
        name: database
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: database        
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
      volumes:
      - name: repository
        persistentVolumeClaim:
          claimName: repository
